# arm64: https://docs.docker.com/desktop/troubleshoot/known-issues/
# nvidia gpus: https://docs.docker.com/compose/gpu-support/

services:
  main:
    container_name: main
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace
    ports:
      - '8888:8888'
    build:
      context: .
      dockerfile_inline: |
        FROM --platform=linux/amd64 ubuntu:22.04

        ARG DEBIAN_FRONTEND=noninteractive
        RUN apt-get update
        RUN apt-get install -y ca-certificates
        RUN apt-get install -y python3 python3-pip

        WORKDIR /workspace
        # COPY requirements.txt /workspace/requirements.txt
        RUN pip3 install --upgrade pip
        # RUN pip3 install -r requirements.txt


        RUN apt-get install -y bash curl git libsqlite3-0 libsqlite3-dev sqlite3 tar wget less vim g++ build-essential make protobuf-compiler libprotobuf-dev

        RUN pip3 install torch numpy pandas scipy nltk scikit-learn joblib langid fasttext wikipedia2vec pyarrow fastparquet future word2number names-dataset gensim gcld3

        RUN pip install --upgrade pip
        RUN pip install git+https://github.com/informagi/REL

        RUN mkdir -p /.rel_cache /.flair
        RUN chmod 777 /.rel_cache /.flair

        RUN mkdir -p /usr/local/share/nltk_data

        RUN [ "python3", "-c", "import nltk; nltk.download('punkt', download_dir='/usr/local/share/nltk_data'); import nltk; nltk.download('averaged_perceptron_tagger', download_dir='/usr/local/share/nltk_data'); nltk.download('stopwords', download_dir='/usr/local/share/nltk_data'); nltk.download('wordnet', download_dir='/usr/local/share/nltk_data'); nltk.download('omw-1.4', download_dir='/usr/local/share/nltk_data')"]

        CMD pip freeze > requirements.txt && tail -f /dev/null
