# arm64: https://docs.docker.com/desktop/troubleshoot/known-issues/
# nvidia gpus: https://docs.docker.com/compose/gpu-support/

services:
  main:
    container_name: main
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace
    ports:
      - '8888:8888'
    build:
      context: .
      dockerfile_inline: |
        FROM --platform=linux/amd64 ubuntu:20.04

        ARG DEBIAN_FRONTEND=noninteractive

        # 
        # experiments
        # 

        # latest python for pytorch 1.6.0
        RUN apt-get update
        RUN apt-get install -y software-properties-common
        RUN add-apt-repository ppa:deadsnakes/ppa
        RUN apt-get update
        RUN apt-get install -y python3.8 python3.8-dev python3.8-distutils
        RUN apt-get install -y python3-pip

        # pytorch 1.6.0 (cpu version)
        RUN pip3 install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

        RUN apt-get update && apt-get install -y --no-install-recommends \
          bash \
          curl \
          git \
          libsqlite3-0 \
          libsqlite3-dev \
          sqlite3 \
          tar \
          wget \
          less \
          vim \
          python3-pip \
          g++ \
          build-essential \
          make \
          protobuf-compiler \
          libprotobuf-dev

        # commit from around march 2022 when this was written
        RUN pip install git+https://github.com/informagi/REL@e81066299e7a19a3a65a0e05d68d90dacef317d3
        RUN mkdir -p /.rel_cache /.flair
        RUN chmod 777 /.rel_cache /.flair

        RUN pip install \
          numpy>=1.21.5 \
          pandas>=1.3.5 \
          scipy>=1.7.3 \
          nltk>=3.4 \
          scikit-learn>=1.0.2 \
          joblib>=1.1.0 \
          langid>=1.1.6 \
          fasttext>=0.9.2 \
          gcld3>=3.0.13 \
          wikipedia2vec>=1.0.5 \
          pyarrow>=6.0.1 \
          fastparquet>=0.7.2 \
          future>=0.18.2 \
          word2number>=1.1 \ 
          names-dataset>=3.0.2

        RUN mkdir -p /usr/local/share/nltk_data
        RUN [ "python3", "-c", "import nltk; nltk.download('punkt', download_dir='/usr/local/share/nltk_data'); import nltk; nltk.download('averaged_perceptron_tagger', download_dir='/usr/local/share/nltk_data'); nltk.download('stopwords', download_dir='/usr/local/share/nltk_data'); nltk.download('wordnet', download_dir='/usr/local/share/nltk_data'); nltk.download('omw-1.4', download_dir='/usr/local/share/nltk_data')"]

        # 
        # evaluation
        # 

        # FROM tomcat:9.0.30-jdk8-openjdk
        RUN apt-get update && \
          apt-get install -y \
          openjdk-8-jdk \
          wget \
          curl \
          && rm -rf /var/lib/apt/lists/*

        RUN mkdir -p /opt/tomcat && \
          wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz -P /tmp && \
          tar xzvf /tmp/apache-tomcat-9.0.30.tar.gz -C /opt/tomcat --strip-components=1 && \
          rm /tmp/apache-tomcat-9.0.30.tar.gz

        RUN groupadd tomcat && \
          useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat && \
          chown -R tomcat:tomcat /opt/tomcat

        # 
        # bugfix
        # 

        # REL dependency missmatch
        RUN pip install flair==0.11.3 transformers==4.11.1 huggingface-hub==0.0.17
        RUN pip install numpy==1.24.4

        # dump dependencies, stay alive
        CMD pip freeze > requirements.txt && tail -f /dev/null
